#!/bin/sh
#
# ./fw: Simple script to enable/disable firewall6. -AndrewX

fw_loc_dir="/etc/fw/v6"
fw_run_file="rc.firewall6"
iptool="/sbin/ip6tables"

echo
echo "AX6-firewall v1.0 by AndrewX"
echo

case "$1" in
  'e')  if [ -f $fw_loc_dir/$fw_run_file ]; then
           $fw_loc_dir/$fw_run_file
        else
           echo "error: $fw_run_file not found."
           echo
        fi
        ;;
  'd')  echo "setting default policies to accept."
        $iptool -P INPUT ACCEPT
        $iptool -P OUTPUT ACCEPT
        $iptool -P FORWARD ACCEPT
        echo "flushing rulesets."
        $iptool -F
        echo "firewall disabled."
        echo
        ;;
  'r')  $iptool -P INPUT ACCEPT
        $iptool -P OUTPUT ACCEPT
        $iptool -P FORWARD ACCEPT
        $iptool -F
        if [ -f $fw_loc_dir/$fw_run_file ]; then
           $fw_loc_dir/$fw_run_file
        else
           echo "error: $fw_run_file not found."
           echo
        fi
        ;;
  'l')  $iptool -L -v -n
        ;;
  *)    echo "Syntax: fw [ e | d | r | l ]"
        echo
        echo "(e=enable, d=disable, r=restart, l=list rules)"
        echo
        ;;
esac

